name: Release On Tag

on:
  push:
    tags:
      # Only match tags that look like go module tags.
      # This way we explicitly ignore our legacy tagging of the operator.
      - '*/v*'
      - '*/*/v*'
  workflow_dispatch:
    inputs:
      ref_name:
        description: "The ref name to process (e.g., 'operator/v1.2.3')"
        required: false
        default: ""

jobs:
  release:
    name: Create Release on GitHub
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "It's working"
      # for testing purposes and to allow updating of pre-existing releases,
      # this workflow can be triggered by a tag being pushed or directly. This
      # step normalized the possible inputs into a single variable.
      - name: get ref
        id: get_ref
        run: |
          if [[ -n "${{ inputs.ref_name }}" ]]; then
            tag="${{ inputs.ref_name }}"
          else
            tag="${{ github.ref_name }}"
          fi
          echo "using ref name: $tag"
          echo "ref_name=$tag" >> "$GITHUB_OUTPUT"


